### ISSUE TITLE
运行报错 在获取支付宝邮件时异常 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by IurKwan** [edge-sky/Bills-save#2]
如题，设置好yaml后运行，报错如下，求解答

SMTP服务器连接成功
POP3服务器连接成功
尝试获取邮件
在获取支付宝邮件时异常 'NoneType' object has no attribute 'groups'
15秒后重试
Traceback (most recent call last):
  File "/Bills-save/mail.py", line 316, in get_mails
    mails_of_alipay = server.get_mails(subject='支付宝交易流水明细',
  File "/Bills-save/.venv/lib/python3.10/site-packages/zmail/server.py", line 141, in get_mails
    headers = self.get_headers(start_index, end_index)
  File "/Bills-save/.venv/lib/python3.10/site-packages/zmail/server.py", line 194, in get_headers
    _, _headers, *__ = parse_headers(mail_header)
  File "/Bills-save/.venv/lib/python3.10/site-packages/zmail/parser.py", line 258, in parse_headers
    headers['date'] = fmt_date(headers['date'])
  File "/Bills-save/.venv/lib/python3.10/site-packages/zmail/parser.py", line 115, in fmt_date
    tz = _fmt_date_tz(time_zone)
  File "/Bills-save/.venv/lib/python3.10/site-packages/zmail/parser.py", line 91, in _fmt_date_tz
    match_groups = TIMEZONE_PATTERN.match(tz).groups()
AttributeError: 'NoneType' object has no attribute 'groups'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Bills-save/main.py", line 27, in <module>
    result = get_mails(receive_time, server)
  File "/Bills-save/mail.py", line 331, in get_mails
    time.sleep(15)
KeyboardInterrupt

**Comment by edge-sky** [comment]
看起来是时区匹配中出现了问题，服务邮箱是否已经收到支付宝的账单邮件？可否尝试打印接收到的邮件的&nbsp;header&nbsp;信息？


---Original---
From: ***@***.***&gt;
Sent at: 2024年9月24日(Tue) AM9:33
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [edge-sky/Bills-save] 运行报错 在获取支付宝邮件时异常 'NoneType' object has no attribute 'groups' (Issue #2)




 
如题，设置好yaml后运行，报错
 在获取支付宝邮件时异常 'NoneType' object has no attribute 'groups'
 
&mdash;

**Comment by IurKwan** [comment]
原因是邮箱中某些邮件的时区格式zmail库解析错误，已经解决，感谢

**Comment by HuangYunHUST** [comment]
大佬你好，我可能遇到了同样的问题，我前两个一星期已经成功运行过了该程序，但是今天准备更新账单时却出现了跟你一样的报错“在获取支付宝邮件时异常 'NoneType' object has no attribute 'groups' ”，可能也是获取邮件的问题，参考大佬的回复，我删除了自从上次成功运行以来的所有邮件，或者更换接受邮箱，但是都没有成功，依然报了同样的错误。请问大佬这应该如何解决呀？

![Image](https://github.com/user-attachments/assets/20ec106c-dd69-442f-9091-e6d5f5c9d394)
