### ISSUE TITLE
支付宝账单报错

### ISSUE THREAD

**Issue by bdingtech** [edge-sky/Bills-save#9]
Traceback (most recent call last):
  File "/Users/pudding/dev/Bills-save/main.py", line 55, in <module>
    is_successes = sync_bills(server, platform, alipay_data(path))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pudding/dev/Bills-save/notion.py", line 126, in sync_bills
    bill_list = check_contrast(platform)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pudding/dev/Bills-save/notion.py", line 115, in check_contrast
    if data['properties']['交易平台']['select']['name'] == platform:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: '交易平台'

**Comment by bdingtech** [comment]
找到原因了，因为我最开始导入的是支付宝的数据，然后再导入的微信，所以导致在校验重复数据的时候，获取到的最近100天的数据，确实没有支付宝的。最终导致报错

**Comment by bdingtech** [comment]
![CleanShot 2024-10-24 at 12 37 20@2x](https://github.com/user-attachments/assets/589f6367-d365-44de-8985-1182e50d44b1)
如果误添加了一项空的，会导致以上报错
